contract: aramis_preprocess_train_config_v0_1
preprocess_train:
  name: aramis_m2q_t100_preprocess_train
  created_by: Sergey Denisov
  output_folder: ./examples/outputs/preprocess_train
preprocessing_config_path: ./config/preprocessing/aramis_biopsy_patients_model_input_v0_1.yaml
training_config_path: ./config/training/aramis_m2q_t100_primary_train_v0_1.yaml
