"""Aramis product draft package."""

from .mlflow_tracking import (
    DEFAULT_EXPERIMENT_NAME,
    build_run_name,
    dataset_fingerprint,
    log_product_run,
)
from .modeling import (
    FusionModelComparisonResult,
    OneToManyProductComparisonResult,
    OneToManyProductLogisticResult,
    RepeatedLogisticResult,
    aggregate_measurement_scores_by_specimen,
    build_fusion_feature_table,
    compute_binary_thresholds,
    default_fusion_feature_sets,
    fit_repeated_fusion_logistic_models,
    fit_repeated_one_to_many_product_feature_ablation_comparison,
    fit_repeated_one_to_many_product_logistic_comparison,
    fit_repeated_one_to_many_product_logistic,
    fit_repeated_one_to_many_logistic,
    fusion_ablation_feature_sets,
    load_one_to_many_dataframe,
    model_matrix,
    profile_matrix,
    summarize_one_to_many_datasets,
    summarize_one_to_many_dataframe,
    summarize_one_to_many_product_results,
)
from .pipelines import (
    AramisPreprocessingPipeline,
    run_preprocessing_pipeline,
    run_preprocessing_from_config,
)
from .prediction import run_prediction_from_config
from .training import (
    AramisPatientTrainingPipeline,
    PatientModelInputBuilder,
    PatientModelSetEvaluator,
    PatientModelSetTrainer,
    build_patient_training_pipeline,
    run_training_from_config,
)
from .workflows import run_workflow_from_config

__all__ = [
    "DEFAULT_EXPERIMENT_NAME",
    "AramisPatientTrainingPipeline",
    "AramisPreprocessingPipeline",
    "FusionModelComparisonResult",
    "OneToManyProductComparisonResult",
    "OneToManyProductLogisticResult",
    "PatientModelInputBuilder",
    "PatientModelSetEvaluator",
    "PatientModelSetTrainer",
    "RepeatedLogisticResult",
    "aggregate_measurement_scores_by_specimen",
    "build_fusion_feature_table",
    "build_patient_training_pipeline",
    "build_run_name",
    "compute_binary_thresholds",
    "dataset_fingerprint",
    "default_fusion_feature_sets",
    "fit_repeated_fusion_logistic_models",
    "fit_repeated_one_to_many_product_feature_ablation_comparison",
    "fit_repeated_one_to_many_product_logistic_comparison",
    "fit_repeated_one_to_many_product_logistic",
    "fit_repeated_one_to_many_logistic",
    "fusion_ablation_feature_sets",
    "load_one_to_many_dataframe",
    "log_product_run",
    "model_matrix",
    "profile_matrix",
    "run_preprocessing_pipeline",
    "run_preprocessing_from_config",
    "run_prediction_from_config",
    "run_training_from_config",
    "run_workflow_from_config",
    "summarize_one_to_many_datasets",
    "summarize_one_to_many_dataframe",
    "summarize_one_to_many_product_results",
]
